import { Progress } from "flowbite-react";
import { FC } from "react";

const Skills: FC = () => {
  return (
    <div className="container mx-auto lg:py-20 md:py-10 py-5">
      <h1 className="lg:text-6xl md:text-5xl text-4xl text-center font-bold uppercase my-5 md:mb-20 mb-10">
        Skills
      </h1>
      <div className="md:grid grid-cols-2 gap-20">
        <Progress
          progress={50}
          labelProgress={true}
          textLabel="Flowbite"
          labelText={true}
          size="lg"
          className="my-2"
        />
        <Progress
          progress={50}
          labelProgress={true}
          textLabel="Flowbite"
          labelText={true}
          size="lg"
          className="my-2"
        />
        <Progress
          progress={50}
          labelProgress={true}
          textLabel="Flowbite"
          labelText={true}
          size="lg"
          className="my-2"
        />
        <Progress
          progress={50}
          labelProgress={true}
          textLabel="Flowbite"
          labelText={true}
          size="lg"
          className="my-2"
        />
        <Progress
          progress={50}
          labelProgress={true}
          textLabel="Flowbite"
          labelText={true}
          size="lg"
          className="my-2"
        />
        <Progress
          progress={50}
          labelProgress={true}
          textLabel="Flowbite"
          labelText={true}
          size="lg"
          className="my-2"
        />
        <Progress
          progress={50}
          labelProgress={true}
          textLabel="Flowbite"
          labelText={true}
          size="lg"
          className="my-2"
        />
        <Progress
          progress={50}
          labelProgress={true}
          textLabel="Flowbite"
          labelText={true}
          size="lg"
          className="my-2"
        />
        <Progress
          progress={50}
          labelProgress={true}
          textLabel="Flowbite"
          labelText={true}
          size="lg"
          className="my-2"
        />
        <Progress
          progress={50}
          labelProgress={true}
          textLabel="Flowbite"
          labelText={true}
          size="lg"
          className="my-2"
        />
        <Progress
          progress={50}
          labelProgress={true}
          textLabel="Flowbite"
          labelText={true}
          size="lg"
          className="my-2"
        />
        <Progress
          progress={50}
          labelProgress={true}
          textLabel="Flowbite"
          labelText={true}
          size="lg"
          className="my-2"
        />
        <Progress
          progress={50}
          labelProgress={true}
          textLabel="Flowbite"
          labelText={true}
          size="lg"
          className="my-2"
        />
        <Progress
          progress={50}
          labelProgress={true}
          textLabel="Flowbite"
          labelText={true}
          size="lg"
          className="my-2"
        />
      </div>
    </div>
  );
};

export default Skills;
